sudo: required

services:
  - docker

install:
  - docker pull ubuntu:16.04

script:
  - docker build -t meteogroup/concourse-ci .
  - docker-compose up -d
  - sleep 20
  - ./test.sh --net container:concourseci_concourse-web_1

after_success:
  - docker-compose stop

after_failure:
  - docker-compose stop
  - docker-compose logs
